apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: depl-nginx
  namespace: default
spec:
  selector:
    matchLabels:
      run: nginx-v2
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-v2
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.14-alpine
        imagePullPolicy: Never
        ports:
        - name: httpd
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels: 
    run: nginx-svc
spec:
  selector:
    run: nginx-v2
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30000
    targetPort: 80
    port: 80
