apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: default
  labels: 
    run: nginxsvc
spec:
  selector:
    run: nginx
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30000
    targetPort: 80
    port: 80
